# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r_packages:
  - covr

r_github_packages:
  - r-lib/pkgdown

before_install:
  - sudo curl -s -L https://entrust.com/root-certificates/entrust_l1k.cer -o /usr/local/share/ca-certificates/entrust_l1k.crt
  - sudo update-ca-certificates

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'pkgdown::build_site()'
